kind: pipeline
type: docker
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet build

- name: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet test
 
- name: publish
  image: docker/compose
  commands:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml push
  volumes:
    - name: dockersock
      path: /var/run/docker.sock    


volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock