kind: pipeline
type: docker
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet build

- name: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet test
 
- name: publish
  image: docker/compose
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker-compose -f docker-compose.yml  build
    - echo $DOCKER_USERNAME
    - echo ${DOCKER_PASSWORD}
  volumes:
    - name: docker_socket
      path: /var/run/docker.sock
 

volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock

image_pull_secrets:
    - dockerconfigjson