kind: pipeline
type: docker
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet build

- name: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet test
 
- name: publish
  image: docker/compose
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - docker-compose -f docker-compose.yml  build
    - docker login inendless.azurecr.io -u $DOCKER_USERNAME  -p $DOCKER_PASSWORD
    - docker-compose push
  volumes:
    - name: docker_socket
      path: /var/run/docker.sock

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 172.27.219.233
    username: vagrant
    password: vagrant
    port: 22
    script:
      - cd ~/deploy
      - git fetch --all
      - git reset --hard origin/main
      - git pull origin main
 

volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock

image_pull_secrets:
    - dockerconfigjson