kind: pipeline
type: docker
name: default

steps:
- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet build

- name: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
    - dotnet test


- name: publish
  image: plugins/docker
  settings:
    username: 
       from_secret: docker_username
    password: 
       from_secret: docker_password
    repo: inendless.azurecr.io/zero/logging.api
    tags: latest
    registry: inendless.azurecr.io

volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock