kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker/compose
  commands:
    - docker-compose -f docker-compose.yml  build
  volumes:
    - name: docker_socket
      path: /var/run/docker.sock

steps:
- name: publish
  image: plugins/docker
  settings:
    username: docker_username
    password: docker_password
    repo: inendless.azurecr.io/zero/logging.api
    tags: latest
    registry: inendless.azurecr.io

volumes:
    - name: docker_socket
      host:
        path: /var/run/docker.sock