version: '3.3'

services:
  logging-api:
    image: inendless.azurecr.io/logging.api
    build:
      context: .
      dockerfile: src/Logging.API/Dockerfile
    ports:
      - "5000:80"
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
